// Memory Testbench:

module tb;
	reg clk, rst;
	mem_env env;
	mem_intrf pif(clk, rst);	// pif is an instance. 
	//we can't declare ports in TB, so declare them using interface.

	//mem dut(.clk	(pif.clk),
	//		.rst	(pif.rst),
	//		.addr	(pif.addr),
	//		.wr_rd	(pif.wr_rd),
	//		.Wdata	(pif.Wdata),
	//		.Rdata	(pif.Rdata),
	//		.valid	(pif.valid),
	//		.ready	(pif.ready));

	mem dut(pif.design_mp);
	mem_assert uut(.clk	(pif.clk),
			.rst	(pif.rst),
			.addr	(pif.addr),
			.wr_rd	(pif.wr_rd),
			.Wdata	(pif.Wdata),
			.Rdata	(pif.Rdata),
			.valid	(pif.valid),
			.ready	(pif.ready));

	always #5 clk = ~clk;
	initial begin
		$display("TB Funtioning");
		clk = 0;
		rst = 1;
		repeat(2) @(posedge clk);
		rst = 0;
		$value$plusargs("test_name=%0s", mem_common::test_name);
		$value$plusargs("N=%0d", mem_common::N);
		env = new();
		env.run();
	end
	initial begin
		//	#2000; if the execution ends at 1500, remaining 500 will be wasted. So, we can terminate execution in another way. By: if tx's generated by GEN and tx's recieved by BFM are equal, then we can terminate the program. i.e., gen_count==bfm_count
		#20;
		wait(mem_common::gen_count==mem_common::bfm_count);		// initially they're 0, so 20 dealy is provided to get make ENV gets started.
		#50;		// to complete last transaction, we need some delay after termination
		
		if(mem_common::matchings!=0 && mem_common::mismatchings==0) begin
			$display("Test passed");
			$display("Matchings = %0d , Mismatchings = %0d", mem_common::matchings, mem_common::mismatchings);
		end
		else begin
			$display("Test failed");
			$display("Matchings = %0d , Mismatchings = %0d", mem_common::matchings, mem_common::mismatchings);
		end
		$finish;
	end
	initial begin
		$dumplfile("tb.vcd");
		$dumpvars;
	end
endmodule
